name: DeepAntiCheat
version: 1.0
author: [white_cola]
depend:
  - HiPlugin
main: top.whitecola.deepanticheat.DeepAntiCheat
commands: 
  ac:
   usage: /ac [ChildCmd]
permissions:
  dlac.report:
    default: true

